baseURL = 'https://cybermythos.org/'
locale = 'en-us'
title = 'Cybermythos'

[params]
  themeColor = "green"

[languages]
  [languages.en.params]
    title = "Cybermythos"
    subtitle = "A network node for the cybernetic being known as thrungaron"

    [languages.en.params.logo]
      logoText = "Cybermythos"
      logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.imports]]
    path = 'github.com/mirus-ua/hugo-theme-re-terminal'